name: firebase_testing
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-63.1.beta <4.0.0'

dependencies:
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.8.0
  flutter:
    sdk: flutter
  mockito: ^5.4.1

dev_dependencies:
  build_runner: ^2.4.4
  firebase_core: ^2.13.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
